# Generated by Django 5.1.7 on 2025-03-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image_url',
            field=models.CharField(default='D:\\Django\\FoodMenu\\Image_url', max_length=500),
        ),
    ]
