# Generated by Django 5.1.7 on 2025-03-20 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_item_item_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_image_url',
            new_name='item_image',
        ),
    ]
