# Generated by Django 5.1.7 on 2025-03-20 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_rename_item_image_url_item_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_image',
        ),
    ]
