# Generated by Django 5.1.7 on 2025-03-20 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_item_item_image_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_image_link',
        ),
    ]
