# Generated by Django 5.1.7 on 2025-03-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_remove_item_item_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image_link',
            field=models.CharField(default='D:\\Django\\FoodMenu\\Image_url\\default_food.jpg', max_length=500),
        ),
    ]
