# Generated by Django 5.1.7 on 2025-03-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_item_item_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image_link',
            field=models.CharField(default='https://www.thefuzzyduck.co.uk/wp-content/uploads/2024/05/image-coming-soon-placeholder-01-660x660.png', max_length=500),
        ),
    ]
